[package]
name = "rapid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.2", features = ["derive"] }
polars = "0.30.0"
rust-stdf = "0.3.1"
